# Generated by Django 3.2.2 on 2022-02-25 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carrera', models.CharField(max_length=100)),
                ('horarios_cursado', models.CharField(max_length=1024)),
                ('plan_correlatividades', models.CharField(max_length=1024)),
                ('calendario_academico', models.CharField(max_length=1024)),
                ('mesas', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('codigo_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.carreras')),
            ],
        ),
    ]
